apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: ci-deploy
      tier: frontend
  template:
    metadata:
      labels:
        app: ci-deploy
        tier: frontend
    spec:
      containers:
        - name: marumaru-frontend-app
          image: gcr.io/kouzoh-p-vamshi-teja/marumaru-frontend-gke:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: frontend-port
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: frontend-port
  selector:
    app: ci-deploy
    tier: frontend