apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: marumaru
      tier: frontend
  template:
    metadata:
      labels:
        app: marumaru
        tier: frontend
    spec:
      containers:
        - name: marumaru-frontend-app
          image: gcr.io/kouzoh-p-vamshi-teja/marumaru-frontend-gke:v1
          env: 
            - name: BACKEND_URL
              value: "http://marumaru-backend:80"
          command: ["npm", "start"]
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: frontend-port
---
apiVersion: v1
kind: Service
metadata:
  name: marumaru-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: frontend-port
  selector:
    app: marumaru
    tier: frontend